#Learning pandas
import pandas as pd

#Two types of datatype in data

    1-D - Series
    2-D -DataFrame

In [4]:
#Create series in data
import pandas as pd
cars=pd.Series(['punto','linea','ecosport','virtus'])
cars

0       punto
1       linea
2    ecosport
3      virtus
dtype: object

In [6]:
colors=pd.Series(['red','white','brown','blue'])
colors

0      red
1    white
2    brown
3     blue
dtype: object

In [9]:
#Create a DataFrame
car_data=pd.DataFrame({"car_type":cars,"colors":colors})
car_data

car_type colors
0     punto    red
1     linea  white
2  ecosport  brown
3    virtus   blue

#Why NumPy - it is a python list

#Datatypes and attributes
A Quick Introduction to Numerical Data Manipulation with Python and NumPy
What is NumPy?
NumPy stands for numerical Python. It's the backbone of all kinds of scientific and numerical computing in Python.

And since machine learning is all about turning data into numbers and then figuring out the patterns, NumPy often comes into play.

a 6 step machine learning framework along will tools you can use for each step
Why NumPy?
You can do numerical calculations using pure Python. In the beginning, you might think Python is fast but once your data gets large, you'll start to notice slow downs.

One of the main reasons you use NumPy is because it's fast. Behind the scenes, the code has been optimized to run using C. Which is another programming language, which can do things much faster than Python.

The benefit of this being behind the scenes is you don't need to know any C to take advantage of it. You can write your numerical computations in Python using NumPy and get the added speed benefits.

If your curious as to what causes this speed benefit, it's a process called vectorization. Vectorization aims to do calculations by avoiding loops as loops can create potential bottlenecks.

NumPy achieves vectorization through a process called broadcasting.

What does this notebook cover?
The NumPy library is very capable. However, learning everything off by heart isn't necessary. Instead, this notebook focuses on the main concepts of NumPy and the ndarray datatype.

You can think of the ndarray datatype as a very flexible array of numbers.

More specifically, we'll look at:

NumPy datatypes & attributes
Creating arrays
Viewing arrays & matrices (indexing)
Manipulating & comparing arrays
Sorting arrays
Use cases (examples of turning things into numbers)


In [236]:
import numpy as np

# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [237]:
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [238]:
a1.shape


(3,)

In [239]:
np.expand_dims(a1,axis=0)

array([[1, 2, 3]])

In [240]:
#Creating random array using randint

random_array=np.random.randint(0,10,size=(2,3))
random_array

array([[6, 7, 8],
       [9, 5, 9]])

In [241]:
random_array=np.random.random((5,3,2,4))
random_array

array([[[[0.81742803, 0.64367467, 0.19280948, 0.46584249],
         [0.07547188, 0.26587322, 0.61491362, 0.4327988 ]],

        [[0.5188268 , 0.86457206, 0.35981415, 0.56775418],
         [0.58129   , 0.61221716, 0.00497098, 0.36667334]],

        [[0.09398758, 0.2078246 , 0.2348917 , 0.13605582],
         [0.42588402, 0.43432573, 0.6638146 , 0.00814594]]],


       [[[0.33373707, 0.85006363, 0.73411809, 0.16451766],
         [0.67861323, 0.63578966, 0.07597521, 0.95239921]],

        [[0.32576277, 0.00171717, 0.4365337 , 0.62744178],
         [0.81648308, 0.82707959, 0.82079662, 0.57594038]],

        [[0.01873238, 0.00667185, 0.00674871, 0.14760683],
         [0.47783504, 0.4334954 , 0.52067892, 0.93337379]]],


       [[[0.67305615, 0.57106572, 0.6241395 , 0.26212078],
         [0.90139541, 0.73945317, 0.05326743, 0.48351032]],

        [[0.06254227, 0.07805429, 0.53593006, 0.92218463],
         [0.08723078, 0.22138091, 0.15944117, 0.60851697]],

        [[0.13857086, 0.89820267, 0.

In [242]:
#Pseudo random numbers
np.random.seed()
random_array=np.random.random((5,3))
random_array

array([[0.57403362, 0.37899636, 0.20070539],
       [0.3533396 , 0.62105972, 0.02891219],
       [0.11434189, 0.26469767, 0.24992078],
       [0.35240267, 0.547288  , 0.46457667],
       [0.94150858, 0.87511744, 0.29442041]])

In [224]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
power = 40
modulo = 10000
x1 = [(n ** power) % modulo for n in range(8)]
x2 = [(n ** power) % modulo for n in np.arange(8)]
print(x1)

[0, 1, 7776, 8801, 6176, 625, 6576, 4001]


In [226]:
a3,a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [227]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [228]:
a3[0][:1:]

array([[1, 2, 3]])

In [229]:
a4

array([[[[7, 0, 8, 6, 3],
         [9, 3, 5, 6, 0],
         [3, 3, 1, 8, 8],
         [1, 1, 2, 8, 4]],

        [[9, 7, 1, 7, 0],
         [2, 8, 5, 9, 8],
         [3, 4, 1, 0, 0],
         [9, 1, 0, 3, 7]],

        [[5, 1, 1, 4, 7],
         [6, 7, 3, 6, 3],
         [4, 1, 2, 6, 5],
         [0, 5, 0, 2, 3]]],


       [[[4, 8, 3, 6, 3],
         [5, 4, 6, 6, 5],
         [8, 0, 4, 4, 5],
         [7, 6, 2, 2, 5]],

        [[0, 0, 1, 8, 4],
         [0, 4, 5, 2, 8],
         [9, 8, 5, 0, 9],
         [1, 5, 3, 2, 8]],

        [[9, 3, 0, 6, 1],
         [5, 9, 9, 1, 1],
         [8, 9, 4, 1, 9],
         [4, 8, 1, 9, 7]]]])

In [230]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[2, 1, 0, 6, 6],
         [3, 7, 5, 2, 4],
         [5, 5, 2, 4, 9],
         [2, 1, 5, 9, 5]],

        [[6, 7, 0, 1, 8],
         [5, 7, 2, 2, 1],
         [3, 9, 1, 1, 0],
         [9, 7, 5, 3, 6]],

        [[3, 2, 1, 0, 7],
         [8, 2, 4, 3, 2],
         [1, 9, 6, 5, 3],
         [7, 1, 8, 1, 9]]],


       [[[3, 4, 0, 7, 8],
         [5, 0, 4, 5, 3],
         [6, 3, 6, 9, 8],
         [8, 8, 0, 4, 1]],

        [[7, 3, 8, 8, 2],
         [5, 8, 0, 0, 4],
         [9, 5, 0, 7, 3],
         [5, 6, 7, 0, 3]],

        [[4, 3, 6, 9, 1],
         [5, 3, 0, 1, 5],
         [8, 1, 3, 6, 7],
         [5, 1, 5, 8, 7]]]])

In [231]:
a4[:,:,3:,1:]

array([[[[1, 5, 9, 5]],

        [[7, 5, 3, 6]],

        [[1, 8, 1, 9]]],


       [[[8, 0, 4, 1]],

        [[6, 7, 0, 3]],

        [[1, 5, 8, 7]]]])

In [243]:
a2.shape,a3.shape

((2, 3), (2, 3, 3))

In [233]:
a2=a2

In [235]:
a2,a3

(array([[1. , 4. ],
        [2. , 5. ],
        [3.3, 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [254]:
a2_reshape=a2.reshape(2,3,1)
a2_reshape,a2

(array([[[1. ],
         [2. ],
         [3.3]],
 
        [[4. ],
         [5. ],
         [6.5]]]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [261]:
a2.shape,a2_reshape.shape

((2, 3), (2, 3, 1))

In [262]:
a2_reshape,a2

(array([[[1. ],
         [2. ],
         [3.3]],
 
        [[4. ],
         [5. ],
         [6.5]]]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [264]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [266]:
a9=np.array([4,5,2])
a9

array([4, 5, 2])

In [267]:
np.argsort(a9)

array([2, 0, 1])

In [269]:
np.argmax(a9)

1

In [282]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [283]:
np.argmax(a2,axis=0)

array([1, 1, 1])

In [284]:
np.argmax(a2,axis=1)

array([2, 2])